# The processes may not start correctly sometimes, you can run reset.sh and rerun the docket-compose
# I believe it is due to the health check criteria isn't perfect
version: "3.7"

services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    networks:
      - elastic
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
    user: "0"
    env_file:
      - .env
    command: >
      bash -c '        
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: ${PUBLIC_V4HOST}\n"\
          "    dns:\n"\
          "      - ${PUBLIC_V4HOST}\n"\
          "    ip:\n"\
          "      - ${PUBLIC_V4IP}\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 777 \{\} \;;
        find . -type f -exec chmod 666 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://${PUBLIC_V4HOST}:9200 | grep -q "missing authentication credentials"; do echo "Waiting es-container up..."; sleep 2; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:open-sesame" -H "Content-Type: application/json" https://${PUBLIC_V4HOST}:9200/_security/user/kibana_system/_password -d "{\"password\":\"password\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/${PUBLIC_V4HOST}/${PUBLIC_V4HOST}.crt ]"]
      interval: 5s
      timeout: 5s
      retries: 120  
      start_period: 20s

  es-container:
    depends_on:
      - setup
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    restart: always
    user: "1000"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/usr/share/elasticsearch/config/certs
    env_file:
      - .env
    environment:
      - ES_JAVA_OPTS=-Xms3g -Xmx4g
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/${PUBLIC_V4HOST}/${PUBLIC_V4HOST}.key
      - xpack.security.http.ssl.certificate=certs/${PUBLIC_V4HOST}/${PUBLIC_V4HOST}.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/${PUBLIC_V4HOST}/${PUBLIC_V4HOST}.key
      - xpack.security.transport.ssl.certificate=certs/${PUBLIC_V4HOST}/${PUBLIC_V4HOST}.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate      
      - discovery.type=single-node
      - ELASTIC_PASSWORD=open-sesame
    networks:
      - elastic
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://${PUBLIC_V4HOST}:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.4.3
    restart: always
    user: "1000"
    env_file:
      - .env
    volumes:
      - ./certs:/usr/share/kibana/config/certs      
      - ./kibana-data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=https://${PUBLIC_V4HOST}:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=password
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt      
      - ENTERPRISESEARCH_HOST=http://${PUBLIC_V4HOST}:3002
    depends_on:
      - setup
      - es-container
    networks:
      - elastic
    ports:
      - 5601:5601
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s -I http://${PUBLIC_V4HOST}:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120      
      
  enterprisesearch:
    container_name: enterprise-search
    depends_on:
      - kibana
    env_file:
      - .env
    restart: always
    user: "1000"
    image: docker.elastic.co/enterprise-search/enterprise-search:8.4.3
    volumes:
      - ./certs:/usr/share/enterprise-search/config/certs
      - ./enterprisesearch-data:/usr/share/enterprise-search/data
    ports:
      - 3002:3002
    networks:
      - elastic
    environment:
      - SERVERNAME=enterprise-search
      - secret_management.encryption_keys=["secret"]
      - allow_es_settings_modification=true
      - elasticsearch.host=https://${PUBLIC_V4HOST}:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=open-sesame
      - elasticsearch.ssl.enabled=true
      - elasticsearch.ssl.certificate_authority=/usr/share/enterprise-search/config/certs/ca/ca.crt
      - kibana.external_url=http://${PUBLIC_V4HOST}:5601
      - ent_search.external_url=http://${PUBLIC_V4HOST}:3002
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s -I http://${PUBLIC_V4HOST}:3002 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  frontend:
    image: frontend:latest
    container_name: frontend
    depends_on:
      - enterprisesearch
    build:
      context: ./frontend
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "80:3000"

  soop_postgres:
    image: soop_postgres:latest
    container_name: soop_postgres
    depends_on:
      - enterprisesearch
    build:
      context: ./soop-sst-postgres
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "8080:3000"

volumes:
  enterprisesearch-data:
    driver: local
  elasticsearch-data:
    driver: local  
  certs:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
